# Generated by Django 3.2.11 on 2022-02-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoviewflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping',
            name='foods',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
